### ISSUE TITLE
nesting

### ISSUE THREAD

**Issue by timoxley** [yoshuawuyts/wayfarer#21] opened 2015-06-14 13:52 UTC
So below is how I expected the nesting API to work on first glance.
In fact, I'm really not sure how it works now haha, can you elaborate on the design?

```js
import wayfarer from 'wayfarer'

const userRouter = wayfarer()
const repoRouter = wayfarer()

userRouter.on('/user/:user', repoRouter)
repoRouter.on('/:repo', params => {
  console.log(params.user, params.repo)
})

userRouter('/user/yoshuawuyts/wayfarer')
// expected:
// => yoshuawuyts wayfarer
// actual:
// => undefined ''

const commitRouter = wayfarer() 
commitRouter.on('/commit/:hash', params => {
  console.log(params.user, params.repo, params.hash)
})

repoRouter.on('/:repo', commitRouter)
userRouter('/user/yoshuawuyts/wayfarer/commit/cda1eaa8')
// expected:
// => yoshuawuyts wayfarer cda1eaa8
// actual:
// AssertionError: path wayfarer/commit/cda1eaa8 did not match
```

**Comment by yoshuawuyts** [comment] 2015-06-14 19:28
Your assumptions are valid, this is how nesting is intended to work. The fact that it doesn't means that there's a bug in there. Will update the test scenarios, and try to fix it. Thanks for reporting!

**Comment by yoshuawuyts** [comment] 2015-06-14 19:40
Right, found out what's failing. Apparently `'/user/:user'` isn't handled properly. `/:user` is. Adding new test cases && fixing.

**Comment by yoshuawuyts** [comment] 2015-06-14 23:18
Released as `wayfarer@4.0.1`

**Closed** 2015-06-14 23:17 UTC
Labels: bug, semver-patch

**Comment by yoshuawuyts** [comment] 2015-06-14 23:19
Oh, and new test case added here to prevent regressions - https://github.com/yoshuawuyts/wayfarer/blob/master/test.js#L75-L84

**Comment by timoxley** [comment] 2015-06-15 00:28
Nice one. Great.

FWIW I was originally writing this up as a more realistic example you could use in the readme, your call, but seems best to give at least mildly realistic examples that hint at the domain of problems you intend to solve. Good sources for examples IMO, are things that most devs are intimate with and or use frequently like login/user flows or in this case, github. 

Also worth implementing some `examples/`, most good libs have examples and I find this can help flush out API design for different usecases.

**Comment by yoshuawuyts** [comment] 2015-06-15 00:47
Oh yeah, I'm +1 for `/examples`, think your example would fit in there just fine.

**Comment by yoshuawuyts** [comment] 2015-06-15 00:52
@timoxley ps, I'm adding you as a contrib to reduce my bus factor as I'm flying to AUS in a few weeks ^__^. Also I think you've had solid contributions, but that's secondary :stuck_out_tongue:.
